version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

tvolumes:
  db_data: 